[package]
name = "nightcycle/cold-fusion"
description = "A framework inspired by Elttob's Fusion allowing for chained states and explicit memory management"
license = "MIT"
authors = ["Elttob", "Nightcycle"]
version = "8.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "nightcycle/signal@^1.0.2"
Maid = "nightcycle/maid@^1.1.4"
ServiceProxy = "nightcycle/service-proxy@^1.0.0"
TableUtil = "nightcycle/table-util@^1.1.0"