[package]
name = "nightcycle/midas"
description = "Turn every game you touch to gold with a comprehensive analytics suite!"
version = "2.0.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Signal = "nightcycle/signal@^1.0.2"
Maid = "nightcycle/maid@1.1.4"
Fetchu  = "nightcycle/fetchu@^1.0.1"
NetworkUtil = "nightcycle/network-util@1.7.0"
TableUtil = "nightcycle/table-util@1.1.0"
ServiceProxy = "nightcycle/service-proxy@1.0.0"