[tools]
remodel = {source = "rojo-rbx/remodel", 		version = "0.11.0" }
wally = 	{source = "UpliftGames/wally", 		version = "0.3.1" }
tarmac = 	{source = "Roblox/tarmac",			version = "0.7.0"}
wally-package-types = {source = "JohnnyMorganz/wally-package-types", version = "1.2.0"}
stylua = {source = "JohnnyMorganz/StyLua", version = "0.15.3"}
wally-update = {source = "nightcycle/wally-update", version = "0.1.2"}
style-guide = {source = "nightcycle/style-guide", version = "0.1.19"}
pseudo-enum = {source = "nightcycle/pseudo-enum", version = "0.1.3"}

[tools.rojo]
source = "rojo-rbx/rojo"
version = "7.0.0"