[package]
name = "nightcycle/format"
description = "why learn basic xml when you can instead just type like you're using discord"
version = "0.1.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
string = "nightcycle/string@0.1.0"
signal = "nightcycle/signal@^1.0.1"
maid = "nightcycle/maid@^1.0.2"
