title = "cold-fusion"  # From Git
gitRepoUrl = "https://github.com/nightcycle/cold-fusion" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/logo.png"

# From git:
organizationName = "nightcycle"
projectName = "cold-fusion"
url = "https://nightcycle.github.io"
baseUrl = "/cold-fusion/"
tagline = "A wrapper for Fusion with some quality of life improvements."

[footer]
style = "dark"
copyright = "Copyright © 2022 Nightcycle Studios LLC. Built with Moonwave and Docusaurus"
