[tools]
remodel = 	{source = "rojo-rbx/remodel", 			version = "0.9.1" }
rojo = 		{source = "rojo-rbx/rojo", 				version = "7.1.0" }
wally = 	{source = "UpliftGames/wally", 			version = "0.3.1" }
tarmac = 	{source = "Roblox/tarmac",				version = "0.7.0"}
wally-update = {source = "nightcycle/wally-update", version = "0.1.2"}
stylua = {source = "JohnnyMorganz/StyLua", version = "0.15.3"}