[package]
name = "nightcycle/draw"
description = "A port of Quenty's draw module, used frequently in debugging."
version = "1.0.6"
authors = ["CJ Oyer <coyer@nightcycle.us>", "Quenty <rbxquenty@gmail.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]

